version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
      - ./Feature2:/app/Feature2
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - ./Backend/.env
    depends_on:
      - ai-service
      - communication-ai

  ai-service:
    build:
      context: ./services/ai-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./services/ai-service:/app

  communication-ai:
    build:
      context: ./services/communication-ai
      dockerfile: Dockerfile
    ports:
      - "8002:8001"
    volumes:
      - ./services/communication-ai:/app
    env_file:
      - ./Backend/.env

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  ml_vision:
    build:
      context: ./Feature3
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./Feature3:/app
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - ./Backend/.env
    depends_on:
      - backend

networks:
  default:
    name: sankalp_network
